#!/usr/bin/env bash
# .devcontainer/setup.sh
# Runs once after the Codespace container is created.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "╔══════════════════════════════════════════════╗"
echo "║   AuraChat — Codespace bootstrap             ║"
echo "╚══════════════════════════════════════════════╝"

# ── 1. Accept any new Android SDK licences ────────────────────────────────────
echo ""
echo "▶ Accepting Android SDK licences…"
yes | sdkmanager --licenses > /dev/null 2>&1 || true

# ── 2. Install / update required SDK components ──────────────────────────────
echo "▶ Ensuring SDK components are up to date…"
sdkmanager \
  "platform-tools" \
  "platforms;android-36" \
  "build-tools;35.0.0" \
  > /dev/null 2>&1

# ── 3. Create local.properties if it doesn't exist ───────────────────────────
echo "▶ Configuring local.properties…"
if [ ! -f "$REPO_ROOT/local.properties" ]; then
  cat > "$REPO_ROOT/local.properties" <<EOF
# Auto-generated by .devcontainer/setup.sh — do not commit.
sdk.dir=/opt/android-sdk
EOF
  echo "   Created local.properties (sdk.dir=/opt/android-sdk)"
else
  # Ensure sdk.dir is set correctly even if the file already exists
  if ! grep -q "^sdk.dir" "$REPO_ROOT/local.properties"; then
    echo "sdk.dir=/opt/android-sdk" >> "$REPO_ROOT/local.properties"
    echo "   Appended sdk.dir to existing local.properties"
  else
    echo "   local.properties already contains sdk.dir — skipping"
  fi
fi

# ── 4. Inject GEMINI_API_KEY from Codespace secret (if provided) ──────────────
if [ -n "${GEMINI_API_KEY:-}" ]; then
  if ! grep -q "^GEMINI_API_KEY" "$REPO_ROOT/local.properties"; then
    echo "GEMINI_API_KEY=${GEMINI_API_KEY}" >> "$REPO_ROOT/local.properties"
    echo "   Injected GEMINI_API_KEY from Codespace secret ✔"
  else
    echo "   GEMINI_API_KEY already present in local.properties — skipping"
  fi
else
  echo "   ⚠  GEMINI_API_KEY not set. Add it as a Codespace secret"
  echo "      (GitHub → Settings → Codespaces → Secrets) then rebuild."
fi

# ── 5. Warn if google-services.json is missing ───────────────────────────────
if [ ! -f "$REPO_ROOT/app/google-services.json" ]; then
  echo ""
  echo "   ⚠  app/google-services.json is missing."
  echo "      Download it from the Firebase console and place it at:"
  echo "      app/google-services.json"
  echo "      See app/google-services.json.example for the required structure."
fi

# ── 6. Pre-warm Gradle wrapper (downloads Gradle distribution) ────────────────
echo ""
echo "▶ Pre-warming Gradle wrapper (this may take a minute)…"
./gradlew --version --no-daemon --quiet 2>&1 | tail -3

echo ""
echo "✅  Codespace is ready!"
echo "    • Build APK  : ./gradlew assembleDebug"
echo "    • Run tests  : ./gradlew test"
echo "    • Clean      : ./gradlew clean"
