package com.aurachat.domain.model

/**
 * Represents the role of a participant in a chat conversation.
 *
 * - [USER] — a message sent by the human user.
 * - [MODEL] — a message generated by the Gemini AI model.
 */
enum class MessageRole { USER, MODEL }

/**
 * Domain model representing a single chat message within a session.
 *
 * @property id Unique database-generated identifier. Defaults to 0 before persistence.
 * @property sessionId The ID of the [ChatSession] this message belongs to.
 * @property content The text body of the message.
 * @property imageUri Optional local URI for an image the user attached to this message.
 * @property role Whether the message was authored by the user or the AI model.
 * @property timestamp Unix epoch milliseconds when the message was created.
 * @property isStreaming Runtime-only flag indicating the AI is still generating this message.
 *   Never persisted to the database.
 * @property isError True if this message represents a failed AI response. Error messages
 *   are excluded from the history context sent to Gemini on subsequent requests.
 */
data class ChatMessage(
    val id: Long = 0L,
    val sessionId: Long,
    val content: String,
    val imageUri: String? = null,
    val role: MessageRole,
    val timestamp: Long,
    val isStreaming: Boolean = false,
    val isError: Boolean = false,
)
